### 查询
GET http://localhost:5144/item/1


### 参数查询
@id=10
GET http://localhost:5144/item/{{id}}


###添加
POST http://localhost:5144/item
Content-Type: application/json

{
  "name": "PS5",
  "price": 2000,
  "describe": "White"
}


###修改改
PUT http://localhost:5144/item
Content-Type: application/json

{
  "id":999,
  "name": "PS5",
  "price": 2000,
  "describe": "White"
}

### 删除
DELETE http://localhost:5144/item/1




